Indian_states = [['Andhra Pradesh', 'Amaravati'],
['Arunachal Pradesh', 'Itanagar'],
['Assam', 'Dispur'],
['Bihar', 'Patna'],
['Chattisgarh', 'Naya Raipur'],
['Goa', 'Panaji'],
['Gujarat', 'Gandhinagar'],
['Haryana', 'Chandigarh'],
['Himachal Pradesh', 'Shimla'],
['Jhakhand', 'Ranchi'],
['Karnatka', 'Bangalore'],
['Kerala', 'Thiruvananthapuram'],
['Madhya Pradesh', 'Bhopal'],
['Maharashtra', 'Mumbai'],
['Manipur', 'Imphal'],
['Meghalya', 'Shillong'], 
['Mizoram', 'Aizwal'],
['Nagaland', 'Kohima'],
['Odisha', 'Bhubaneshwar'], 
['Punjab', 'Chandigarh'],
['Rajasthan', 'Jaipur'],
['Sikkim', 'Gangtok'],
['Tamil Nadu', 'Chennai'],
['Telangana', 'Hyderabad'],
['Tripura', 'Agartala'],
['Uttar Pradesh', 'Lucknow'],
['Uttarakhand', 'Dehradun'],
['West Bengal', 'Kolkata']]